"""
Output schemas for analysis results.

These models define the normalized response returned by the analysis pipeline.
The schema is designed to support both human-readable reporting and later
machine-driven evaluation of recommendations.
"""

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class ConfidenceLevel(str, Enum):
    """Confidence levels used to communicate certainty in the analysis."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class BottleneckCategory(str, Enum):
    """High-level categories for the primary query bottleneck."""

    SCAN = "scan"
    JOIN = "join"
    SORT = "sort"
    STATS = "stats"
    LOCKING = "locking"
    CONFIG = "config"
    OTHER = "other"


class RecommendationType(str, Enum):
    """Types of remediation or investigation the tool can recommend."""

    INDEX = "index"
    REWRITE = "rewrite"
    STATS = "stats"
    CONFIG = "config"
    INVESTIGATE = "investigate"


class PriorityLevel(str, Enum):
    """Priority levels used to rank issues and recommendations."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class BottleneckSummary(BaseModel):
    """Summary of the primary bottleneck and the evidence behind it."""

    category: BottleneckCategory
    evidence: list[str] = Field(default_factory=list)


class EstimateMismatch(BaseModel):
    """Represents a meaningful mismatch between estimated and actual row counts."""

    node: str
    estimated_rows: float | None = None
    actual_rows: float | None = None
    severity: PriorityLevel
    interpretation: str


class Recommendation(BaseModel):
    """Represents a candidate action generated by the analysis pipeline."""

    type: RecommendationType
    priority: PriorityLevel
    action: str
    rationale: str
    risk: str | None = None
    sql_candidate: str | None = None


class AnalysisOutput(BaseModel):
    """Top-level response returned by the query analysis workflow."""

    summary: str
    confidence: ConfidenceLevel
    primary_bottleneck: BottleneckSummary
    estimate_mismatches: list[EstimateMismatch] = Field(default_factory=list)
    recommendations: list[Recommendation] = Field(default_factory=list)
    verification_steps: list[str] = Field(default_factory=list)
    do_not_do: list[str] = Field(default_factory=list)